### ISSUE TITLE
dnsdict6 is not longer available on Kali 2.x 

### ISSUE THREAD

**Issue by vicendominguez** [1N3/BruteX#1]
Hey!!..... thanks for sharing....

what about using dnsenum instead of dnsdict6?. dnsdict6 is not longer available on Kali 2.x
I think the line is the same calling dnsenum without -4.

:tada:

**Comment by 1N3** [comment]
Hi, thanks for the suggestion... looking into this but it doesn't look like you can parse the results the same as dnsdict and dnsenum seems to take much longer to do reverse lookups on everything... going to keep testing though and probably add this in the next release.

**Comment by 1N3** [comment]
As another alternative, I may just bundle the prebuilt binary for dnsdict6 in with the release since it still seems to work in Kali 2.0. Not ideal, but that may work as well...

**Comment by 1N3** [comment]
v1.2 was released to include dnsenum to replace DNSDict6.. thanks for the heads up!

**Comment by vicendominguez** [comment]
it was the easiest way so it is ok... and you can choose to change it when you want in future versions. Anyway your comment was true... reverse lookups looked like slower.

**Comment by XSecr3t** [comment]
Is this only for root users?
 Cause i found this error in my termux

Are is it compatible for termux? 

Code error :

-- --=[This script will install brutex under /usr/share/brutex.
cp: target '/usr/share/brutex' is not a directory
install.sh: line 26: cd: /usr/share/brutex: No such file or directory
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dnsenum
chmod: cannot access '/usr/share/brutex/brutex': No such file or directory
ln: failed to create symbolic link '/usr/bin/brutex': No such file or directory
 + -- --=[Done!

**Comment by phr34k0** [comment]
> Is this only for root users?
> Cause i found this error in my termux
> 
> Are is it compatible for termux?
> 
> Code error :
> 
> -- --=[This script will install brutex under /usr/share/brutex.
> cp: target '/usr/share/brutex' is not a directory
> install.sh: line 26: cd: /usr/share/brutex: No such file or directory
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package dnsenum
> chmod: cannot access '/usr/share/brutex/brutex': No such file or directory
> ln: failed to create symbolic link '/usr/bin/brutex': No such file or directory
> 
> * -- --=[Done!

Lol, you need "Sudo" to make files and/or directories in /usr/share folder. Normal users need gksudo

**Comment by XSecr3t** [comment]
@phr34k0 already installed but still can't,,

**Comment by phr34k0** [comment]
> @phr34k0 already installed but still can't,,

See your log

> install.sh: line 26: cd: /usr/share/brutex: No such file or directory

Try open up install.sh with a text editor (e.g. geany) and look at the folders it tries to create/copy files to and manually create them. Brutex folder.. Make a symbolic link by "ln -sf" command and do install the dnsenum package since Brutex uses it. My guess is something went wrong during your installation process or it's your linux environment
