### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by toxicdensity** [1N3/BruteX#14]
+ -- --=[ Installing brutex under /usr/share/brutex...
cp: target '/usr/share/brutex' is not a directory
./install.sh: line 26: cd: /usr/share/brutex: No such file or directory
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:3 https://dl.bintray.com/grimler/termux-root-packages-21 root InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:7 https://dl.bintray.com/grimler/termux-root-packages-21 root Release [6185 B]
Hit:7 https://dl.bintray.com/grimler/termux-root-packages-21 root Release
Get:9 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:9 https://dl.bintray.com/grimler/science-packages-21 science Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dnsenum
chmod: cannot access '/usr/share/brutex/brutex': No such file or directory
ln: failed to create symbolic link '/usr/bin/brutex': No such file or directory
 + -- --=[ Done!

**Comment by toxicdensity** [comment]
Plsss help

**Comment by 1N3** [comment]
Did you run the install.sh file as 'root'? Also, can you confirm which OS you're running on?
