### ISSUE TITLE
Failed to open XML output file [Directory/filexml] for writing QUITTING And another "grep:" error 

### ISSUE THREAD

**Issue by tugdualnicolas** [1N3/BruteX#2]
root@kali:~/BruteX# ./brutex [Ip address]

################################### Running Port Scan ##############################
Failed to open XML output file /usr/share/brutex/loot/nmap-[ip address].xml for writing
QUITTING!

################################### Running Brute Force ############################

grep: /usr/share/brutex/loot/nmap-[ip address].xml

**Comment by 1N3** [comment]
Hi, this was something that was changed in the latest version. BruteX now must be installed using the install.sh script which installs brutex to /usr/share/brutex. This allows universal access by simply typing 'brutex <ip>' after which should work. 

Did you download the latest version and run the install.sh? If so, you can just run brutex directly (ie. not ./brutex <ip>) as above.

**Comment by 1N3** [comment]
In the meantime, I will look into making a backward compatible release to run direct from the script repo.

**Comment by tugdualnicolas** [comment]
Its working now thx ! :+1:
