### ISSUE TITLE
Error in building Docker image

### ISSUE THREAD

**Issue by sadra-barikbin** [1N3/BruteX#28]
Hi,
During docker image build these issues arise:
![image](https://user-images.githubusercontent.com/22097587/188288407-4cb87a51-cd96-46e4-8eae-9c603e840761.png)
After some lines:
![image](https://user-images.githubusercontent.com/22097587/188288415-c4aa9976-4b18-4a36-9610-4ec582ed6502.png)
And finally:
![image](https://user-images.githubusercontent.com/22097587/188288429-b27fec7a-062e-45d1-887c-0cc894ea2026.png)

**Comment by 1N3** [comment]
This is fixed now.
