### ISSUE TITLE
hello guys! Brutex error!!

### ISSUE THREAD

**Issue by LazPirin53** [1N3/BruteX#29]
Brutex open target problems!
brutex was to work before.
I opened it to test and it stopped giving an error...
can you please help?
The errors given are in the screenshots. you can look...
system information kali linux...

![Ekran Görüntüsü - 2022-11-19 01-12-47](https://user-images.githubusercontent.com/118119785/202812242-aa1db8fb-807a-4233-9e3e-cc933870dd04.png)

![Ekran Görüntüsü - 2022-11-19 01-13-21](https://user-images.githubusercontent.com/118119785/202812271-09ed3826-7306-482c-a5a7-720b9085f5a8.png)

**Comment by 1N3** [comment]
Syntax is brutex <target IP/hostname/domain>. Don't use URL's.
