### ISSUE TITLE
[*] Installing brutex under /usr/share/brutex... cp: target '/usr/share/brutex': No such file or directory ./install.sh: line 27: cd: /usr/share/brutex: No such file or director

### ISSUE THREAD

**Issue by blornbros** [1N3/BruteX#33]
[*] Installing brutex under /usr/share/brutex...
cp: target '/usr/share/brutex': No such file or directory
./install.sh: line 27: cd: /usr/share/brutex: No such file or directory
Hit:1 https://packages.termux.dev/apt/termux-main stable InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package hydra
E: Unable to locate package dnsenum
chmod: cannot access '/usr/share/brutex/brutex': No such file or directory
ln: failed to create symbolic link '/usr/bin/brutex': No such file or directory
[*] Done!
~/BruteX $

Is this a user error, a configuration issue, permissions issue, or a bug? Can be reproduced faithfully. Have tried upgrades and updates, installing missing dependency packages manually, changing termux package mirrors, and repeating the process. I've tried giving elevated access to install.sh with chmod, and I've googled quite a bit to no avail.

**Comment by 1N3** [comment]
Hi, you need to run the install.sh script as 'root'. I will look at adding code to enforce this in the future.
